### ISSUE TITLE
Use rework-flex-grid

### ISSUE THREAD

**Issue by johnotander** [johnotander/furtive#33]

**Comment by howardroark** [comment]
+1 for this.  I have been playing around and find that I would prefer an even number of columns to get a perfect split screen :)

**Comment by johnotander** [comment]
No doubt, that's the exact reason I created this issue. Hopefully I'll be able to get to it today or tomorrow.

The primary reason I haven't added in the new grid yet is because I will need to add in a changelog since it will, unfortunately, be a breaking change with the current implementation. But I've been hurting for it on my projects that use furtive, for sure.

**Comment by johnotander** [comment]
Aaaand done :smile_cat:

**Comment by howardroark** [comment]
Awesome!  6 column default... I like it!

**Comment by johnotander** [comment]
Yeah, I figured I'd take out one column rather than bumping it up to 8 in order to cut down on CSS, since the latest grid, as a result of the media-queries, is .67kB bigger.

**Comment by howardroark** [comment]
I really like the layout of the top section.  I almost wish `blueprint` was like that.  It makes for a nice splash view of a project.

**Comment by johnotander** [comment]
Agreed. I suspect I will be incorporating something like that into the new implementation.

**Comment by howardroark** [comment]
May as well tie your projects together so they can compliment each other :)

Once you start getting into the new implementation you should setup a `gitter` page.  I love giving feedback :)

**Comment by johnotander** [comment]
Yeah, I definitely need to start working on doing that, haha. I most definitely will, thanks @howardroark
