### ISSUE TITLE
Pseudo-elements use old syntax

### ISSUE THREAD

**Issue by variadico** [johnotander/furtive#40]
Hello! Furtive calls itself a "forward-thinking" microframework.

But, I noticed that pseudo-elements in this project use the obsolete syntax (according to MDN). https://developer.mozilla.org/en-US/docs/Web/CSS/::before

For example, here.
https://github.com/johnotander/furtive/blob/master/css/furtive.css#L426

Could it be reasonable to update the syntax from `foo:before` to `foo::before`? I can submit a pull request if that would help.

**Comment by johnotander** [comment]
Thanks for reporting this. That would be absolutely wonderful, @pi241a !

**Comment by johnotander** [comment]
Closed with #41

**Comment by variadico** [comment]
Just pointing out that your latest commit, [Add red buttons](https://github.com/johnotander/furtive/blob/c6229b69698e726da16c8bcd607554314fe567d1/css/furtive.css#L426), re-introduced the old syntax for pseudo-elements.

FYI.

**Comment by johnotander** [comment]
Thanks for pointing this out @variadico, I'll swap the syntax out today.

**Comment by johnotander** [comment]
Latest version now uses the new syntax.
