### ISSUE TITLE
Add csslinting to build

### ISSUE THREAD

**Issue by johnotander** [johnotander/furtive#43]

**Comment by pi241a** [comment]
I'm not sure what you use for writing code, so this may or may not be useful to you, but Sublime Text has a plugin called CSS3 that could help with the linting.
https://github.com/y0ssar1an/CSS3

That's how I noticed something was up with `word-wrap`.

Anyway, thanks for maintaining this thing!

**Comment by johnotander** [comment]
Thanks for the link. I've been using vim lately, but I should probably track down a similar plugin for that editor. Regardless I'd still like to incorporate csslinting as part of the gulp task, thoroughness never hurts :).

**Comment by pgib** [comment]
[Syntastic](https://github.com/scrooloose/syntastic) is a great vim plug-in for syntax checking on the editor side. It's a front-end for various linting tools, and for SCSS, it uses [scss-lint](https://github.com/brigade/scss-lint).
